[package]
name = "front"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
yew = { version = "^0.20", features = ["csr"] }
yew-router = "0.17"
reqwasm = "0.2"
wasm-bindgen-futures = "0.4"
serde = "^1"
serde_derive = "^1"
serde_json = "1"
log = "0.4.6"
wasm-logger = "^0.2"
reqwest = { version = "0.11", features = ["json"] }
gloo-net = "0.6.0"
